### ISSUE TITLE
Игнорировать строчки с комментариями

### ISSUE THREAD

**Issue by lebe-dev** [lebe-dev/dcft#1]
Сейчас вот такой кусок будет обработан неправильно:

```yaml
 backend:
   # image: my-repo/app-backend:6.2.0
   image: my-repo/app-backend:6.2.1
```
Утилита заменит тэг в строке с комментарием и проигнорит вторую стоку
